[project]
name = "desktop-pet"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Akita", email = "162419584+AkitaCodingPeasant@users.noreply.github.com" }
]
requires-python = ">=3.14"
dependencies = [
    "pyside6>=6.11.2",
]

[project.scripts]
desktop-pet = "desktop_pet.app:main"

[build-system]
requires = ["uv_build>=0.12.10,<0.13.0"]
build-backend = "uv_build"
